### ISSUE TITLE
Why JSON is enforced by default

### ISSUE THREAD

**Issue by greenboxal** [alyssaq/prequest#1]
I spend my whole day trying to debug why I couldn't send an simple XML to an web service :(
Then I discovered that around the line 13 JSON is enforced by default, why?

`options.json = options.hasOwnProperty('json') ? options.json : true;`

**Comment by alyssaq** [comment]
I wrote in the Readme that Json is the default format because its the most common format with APIs (at least for me). 
Sorry that it took you a day to realize this difference - - -  I'll make it more explicit in the Readme.

Ironically,  it took me some time to realize that I had to pass `json:true` in the request module to always do Json.

**Comment by greenboxal** [comment]
I understand your point, but as a wrapper, I think that this library should conform to `request` behaviour.

**Comment by alyssaq** [comment]
I do agree with your point but I'm maintaining this library as part of my stack in building apps and don't plan to change the Json flag. 
I already have a couple of apps that depend on this module and expect Json as default. 

As you've seen, the code is only 30 lines long to combine bluebird and request. 
Do feel free to fork, change the flag and publish in npm. That is afterall the greatness of having open source code and public npm. Thanks for trying out the module.
